import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";

enum AuthStatus {
  LOADING = "loading",
  AUTHENTICATED = "authenticated",
  UNAUTHENTICATED = "unauthenticated",
}
const Home: NextPage = (props) => {
  const { data, status } = useSession();

  console.log("data", data);
  console.log("status", status);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {data?.user?.image && (
          <img src={data?.user.image} className="w-30 h-30 rounded-full" />
        )}
        {data?.user?.name && <p>{data?.user?.name}</p>}
        {data?.user?.email && <p>{data?.user?.email}</p>}
        {data?.user?.id && <p>{data?.user?.id}</p>}
        <div>
          {status === AuthStatus.AUTHENTICATED ? (
            <button onClick={() => signOut()}>Sign Out</button>
          ) : (
            <button onClick={() => signIn()}>Sign in</button>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
